// Stable, machine-readable error codes. Clients branch on these, never on message text.
// Modules add their own codes here so the full catalogue stays in one place (see docs/api.md).
export const ErrorCode = {
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  UNPROCESSABLE: 'UNPROCESSABLE',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Auth (src/modules/auth)
  ACCOUNT_EXISTS: 'ACCOUNT_EXISTS',
  HANDLE_TAKEN: 'HANDLE_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  INVALID_OTP: 'INVALID_OTP',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  ALREADY_VERIFIED: 'ALREADY_VERIFIED',

  // Users (src/modules/users)
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  NAME_LOCKED: 'NAME_LOCKED',
  CONTACT_UNAVAILABLE: 'CONTACT_UNAVAILABLE',
  ACCOUNT_HAS_BALANCE: 'ACCOUNT_HAS_BALANCE',
  ACCOUNT_HAS_PENDING_TRANSACTIONS: 'ACCOUNT_HAS_PENDING_TRANSACTIONS',

  // KYC (src/modules/kyc)
  KYC_TIER_ORDER: 'KYC_TIER_ORDER',
  KYC_TIER_ALREADY_APPROVED: 'KYC_TIER_ALREADY_APPROVED',
  KYC_UNDER_REVIEW: 'KYC_UNDER_REVIEW',
  KYC_STATE_CHANGED: 'KYC_STATE_CHANGED',
  KYC_SELF_REVIEW: 'KYC_SELF_REVIEW',
  KYC_PROVIDER_CHECK_INCOMPLETE: 'KYC_PROVIDER_CHECK_INCOMPLETE',

  // Idempotency (src/common/idempotency)
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_INVALID: 'IDEMPOTENCY_KEY_INVALID',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_REQUEST_IN_PROGRESS: 'IDEMPOTENCY_REQUEST_IN_PROGRESS',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
