// Where KYC document files live. Local disk now, S3 in Stage 25: the service only sees this
// interface. Files are never served over HTTP; reviewers will read them through the API.
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

export interface DocumentStorage {
  /** Fails if the key already exists: a stored document is never overwritten. */
  put(key: string, content: Uint8Array): Promise<void>;
  get(key: string): Promise<Uint8Array>;
  /** Succeeds if the key doesn't exist. */
  delete(key: string): Promise<void>;
}

/** Keys are generated by the service (`<profileId>/<uuid>`), never taken from a request. */
const KEY_PATTERN = /^[0-9a-f-]{36}\/[0-9a-f-]{36}$/;

function assertKey(key: string): void {
  // Defence in depth: a key that isn't ours can't reach outside the storage directory.
  if (!KEY_PATTERN.test(key)) throw new Error('Invalid document storage key');
}

export class LocalDocumentStorage implements DocumentStorage {
  readonly #root: string;

  constructor(root: string) {
    this.#root = resolve(root);
  }

  async put(key: string, content: Uint8Array): Promise<void> {
    assertKey(key);
    const path = join(this.#root, key);
    await mkdir(join(path, '..'), { recursive: true, mode: 0o700 });
    await writeFile(path, content, { flag: 'wx', mode: 0o600 });
  }

  async get(key: string): Promise<Uint8Array> {
    assertKey(key);
    return new Uint8Array(await readFile(join(this.#root, key)));
  }

  async delete(key: string): Promise<void> {
    assertKey(key);
    await rm(join(this.#root, key), { force: true });
  }
}

/** For tests. */
export class MemoryDocumentStorage implements DocumentStorage {
  readonly files = new Map<string, Uint8Array>();

  put(key: string, content: Uint8Array): Promise<void> {
    if (!KEY_PATTERN.test(key)) return Promise.reject(new Error('Invalid document storage key'));
    if (this.files.has(key)) return Promise.reject(new Error('Document already exists'));
    this.files.set(key, content);
    return Promise.resolve();
  }

  get(key: string): Promise<Uint8Array> {
    const content = this.files.get(key);
    return content === undefined
      ? Promise.reject(new Error('Document not found'))
      : Promise.resolve(content);
  }

  delete(key: string): Promise<void> {
    this.files.delete(key);
    return Promise.resolve();
  }
}
