-- Fencing token for idempotency claims (see src/modules/idempotency). Generated by
-- `prisma migrate diff` against a database with all earlier migrations applied.
-- AlterTable
ALTER TABLE "idempotency_keys" ADD COLUMN     "claimed_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
